<% if frontend? %>
watch-css:
	npx tailwindcss -i ./resources/css/screen.css -o ./resources/public/css/screen.css --watch

build-css:
	npx tailwindcss -i ./resources/css/screen.css -o ./resources/public/css/screen.css --watch<% endif %>
